import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";
import React from "react";

interface MemoData {
  title: string;
  goal: string;
  finalScore: number;
  decisions: { label: string; delta: number }[];
  highlights: string[];
  redactionTotal: number;
}

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#111" },
  h1: { fontSize: 18, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  meta: { color: "#666", marginBottom: 14, fontSize: 9 },
  rule: { height: 1, backgroundColor: "#ddd", marginBottom: 14 },
  h2: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 6 },
  p: { marginBottom: 6, lineHeight: 1.45 },
  badge: { padding: 4, backgroundColor: "#f3f3f1", borderRadius: 3, fontSize: 9 },
  itemRow: { flexDirection: "row", marginBottom: 3 },
  bullet: { width: 8 },
});

export async function renderMemoPdf(data: MemoData): Promise<Uint8Array> {
  const doc = (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>{data.title}</Text>
        <Text style={styles.meta}>
          Generated by Gambit · final win bar {data.finalScore.toFixed(1)} ·{" "}
          {data.redactionTotal} item{data.redactionTotal === 1 ? "" : "s"} redacted
        </Text>
        <View style={styles.rule} />

        <Text style={styles.h2}>Goal</Text>
        <Text style={styles.p}>{data.goal || "(not stated)"}</Text>

        <Text style={styles.h2}>Decisions taken</Text>
        {data.decisions.length === 0 ? (
          <Text style={styles.p}>(none)</Text>
        ) : (
          data.decisions.map((d, i) => (
            <View key={i} style={styles.itemRow}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.p}>
                {d.label} ({d.delta > 0 ? "+" : ""}
                {d.delta})
              </Text>
            </View>
          ))
        )}

        <Text style={styles.h2}>Highlights</Text>
        {data.highlights.length === 0 ? (
          <Text style={styles.p}>(none)</Text>
        ) : (
          data.highlights.map((h, i) => (
            <View key={i} style={styles.itemRow}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.p}>{h}</Text>
            </View>
          ))
        )}
      </Page>
    </Document>
  );
  const buf = await renderToBuffer(doc);
  return new Uint8Array(buf);
}
