/**
 * Counter-redline DOCX builder. Server-only.
 *
 * Per docs/tasks/08-will-outbound-work-product.md §"DOCX":
 *   "Acceptable simplification: generate new docx with summary + appendix
 *    quoting clauses — document choice."
 *
 * The output is a clean "Counter-Redline Package" that:
 *   - Names parties + effective date.
 *   - Restates the chosen move (Decision.summaryLegal + summaryPlain).
 *   - Includes a financial table aligned with Decision.financials.
 *   - Lists every Initech redline (R01..R13 / N01..N05) with the exact
 *     Dunder counter-proposal in the Decision's locale.
 *   - Calls out compliance flags + citations from the Decision.
 *
 * Output: Word-compatible .docx bytes (Uint8Array). Verify by opening in
 * Microsoft Word + Google Docs.
 */

import {
  AlignmentType,
  Document,
  HeadingLevel,
  LevelFormat,
  Packer,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
  type IRunOptions,
} from "docx";
import type { Decision, Locale } from "@/lib/contracts";
import {
  counterProposalsFor,
  type CounterProposal,
} from "./counterProposals";

const BRAND_HEX = "FF4B00"; // matches design.MD `--color-brand`
const STRIKE_HEX = "C00000";
const INSERT_HEX = "1B7A3D";
const MUTED_HEX = "666666";

type Block = Paragraph | Table;

interface BuildOpts {
  decision: Decision;
  /** Inferred from the Decision; we keep the contract-kind explicit. */
  documentFocus: "nda" | "msa";
}

export async function buildCounterRedlineDocx(
  opts: BuildOpts,
): Promise<Uint8Array> {
  const { decision, documentFocus } = opts;
  const locale: Locale = decision.locale ?? "en";
  const proposals = counterProposalsFor(documentFocus);
  const today = new Date().toISOString().slice(0, 10);

  const children: Block[] = [
    ...buildHeader(decision, documentFocus, today, locale),
    ...buildMoveSummary(decision, locale),
    ...buildFinancialTable(decision, locale),
    ...buildClauseAppendix(decision, proposals, locale),
    ...buildCitationsBlock(decision, locale),
    ...buildSignatureBlock(locale),
  ];

  const doc = new Document({
    creator: "Gambit",
    title:
      locale === "fr"
        ? "Contre-rougeline — Dunder AI / Initech"
        : "Counter-Redline Package — Dunder AI / Initech",
    description:
      "Generated by Gambit from a Decision payload (T8 — Will).",
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 },
        },
      },
    },
    numbering: {
      config: [
        {
          reference: "wp-list",
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: "%1.",
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  // Buffer is a subclass of Uint8Array; copy to a plain Uint8Array so the
  // contract type matches `Uint8Array` exactly.
  return new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
}

// -----------------------------------------------------------------------------
// helpers
// -----------------------------------------------------------------------------

function t(en: string, fr: string, locale: Locale): string {
  return locale === "fr" ? fr : en;
}

function brandRun(text: string, opts: Partial<IRunOptions> = {}): TextRun {
  return new TextRun({ text, color: BRAND_HEX, bold: true, ...opts });
}

function buildHeader(
  decision: Decision,
  documentFocus: "nda" | "msa",
  today: string,
  locale: Locale,
): Block[] {
  const docKind = documentFocus === "nda" ? "NDA" : "MSA";
  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [
        brandRun(
          t(
            `Counter-Redline Package — ${docKind}`,
            `Contre-rougeline — ${docKind}`,
            locale,
          ),
        ),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: t(
            "Vendor: Dunder AI Inc. — Client: Initech Financial Group Inc.",
            "Fournisseur : Dunder AI Inc. — Client : Initech Financial Group Inc.",
            locale,
          ),
          italics: true,
          color: MUTED_HEX,
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: t(
            `Generated: ${today} • Deal: `,
            `Généré : ${today} • Affaire : `,
            locale,
          ),
          color: MUTED_HEX,
        }),
        new TextRun({ text: decision.dealId, color: MUTED_HEX, bold: true }),
        new TextRun({
          text: t("  • Move: ", "  • Coup : ", locale),
          color: MUTED_HEX,
        }),
        new TextRun({ text: decision.chosenMoveId, color: MUTED_HEX, bold: true }),
      ],
    }),
  ];
}

function buildMoveSummary(decision: Decision, locale: Locale): Block[] {
  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [
        new TextRun(t("1. Move summary", "1. Résumé du coup", locale)),
      ],
    }),
    new Paragraph({
      spacing: { after: 120 },
      children: [new TextRun(decision.summaryLegal)],
    }),
    new Paragraph({
      spacing: { after: 240 },
      children: [
        new TextRun({
          text: t("Plain language: ", "Langage clair : ", locale),
          italics: true,
          color: MUTED_HEX,
        }),
        new TextRun({ text: decision.summaryPlain, italics: true }),
      ],
    }),
  ];
}

function buildFinancialTable(decision: Decision, locale: Locale): Block[] {
  const f = decision.financials;
  const totalCad =
    f.totalContractCad ?? f.monthlyAmount * Math.max(f.months, 1);

  const fmt = new Intl.NumberFormat(locale === "fr" ? "fr-CA" : "en-CA", {
    style: "currency",
    currency: f.currency,
    maximumFractionDigits: 0,
  });

  const row = (label: string, value: string, isHeader = false): TableRow =>
    new TableRow({
      children: [
        new TableCell({
          width: { size: 35, type: WidthType.PERCENTAGE },
          shading: isHeader
            ? { type: ShadingType.SOLID, color: BRAND_HEX, fill: BRAND_HEX }
            : undefined,
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: label,
                  bold: isHeader,
                  color: isHeader ? "FFFFFF" : "111111",
                }),
              ],
            }),
          ],
        }),
        new TableCell({
          width: { size: 65, type: WidthType.PERCENTAGE },
          children: [new Paragraph({ children: [new TextRun(value)] })],
        }),
      ],
    });

  return [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [
        new TextRun(t("2. Financials", "2. Données financières", locale)),
      ],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        row(
          t("Field", "Champ", locale),
          t("Value", "Valeur", locale),
          true,
        ),
        row(t("Currency", "Devise", locale), f.currency),
        row(
          t("Monthly amount", "Montant mensuel", locale),
          fmt.format(f.monthlyAmount),
        ),
        row(
          t("Term (months)", "Durée (mois)", locale),
          String(f.months),
        ),
        row(t("Net days", "Net jours", locale), String(f.netDays)),
        row(t("Tier", "Niveau", locale), f.tier),
        row(t("Seats", "Postes", locale), String(f.seats)),
        row(
          t("Total contract", "Valeur contractuelle totale", locale),
          fmt.format(totalCad),
        ),
      ],
    }),
    new Paragraph({ spacing: { after: 240 }, children: [new TextRun("")] }),
  ];
}

function buildClauseAppendix(
  _decision: Decision,
  proposals: readonly CounterProposal[],
  locale: Locale,
): Block[] {
  const out: Block[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [
        new TextRun(
          t(
            "3. Counter-proposals by clause",
            "3. Contre-propositions par clause",
            locale,
          ),
        ),
      ],
    }),
  ];

  for (const p of proposals) {
    out.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_3,
        children: [
          new TextRun({ text: `${p.id} — `, bold: true, color: BRAND_HEX }),
          new TextRun({ text: p.clauseRef, bold: true }),
        ],
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: t("Initech ask: ", "Demande Initech : ", locale),
            italics: true,
            color: MUTED_HEX,
          }),
          new TextRun({ text: p.initechAsk, color: STRIKE_HEX }),
        ],
      }),
      new Paragraph({
        spacing: { after: 200 },
        children: [
          new TextRun({
            text: t("Dunder counter: ", "Contre Dunder : ", locale),
            italics: true,
            color: MUTED_HEX,
          }),
          new TextRun({
            text: locale === "fr" ? p.dunderCounterFr : p.dunderCounterEn,
            color: INSERT_HEX,
            bold: true,
          }),
          new TextRun({
            text: ` [${p.severity.toUpperCase()}]`,
            color: severityColor(p.severity),
            bold: true,
          }),
        ],
      }),
    );
  }
  return out;
}

function severityColor(s: CounterProposal["severity"]): string {
  switch (s) {
    case "existential":
      return "9C0000";
    case "high":
      return "B85C00";
    case "medium":
      return "8A6D00";
    case "low":
      return "667085";
  }
}

function buildCitationsBlock(decision: Decision, locale: Locale): Block[] {
  if (
    decision.citationsUsed.length === 0 &&
    decision.complianceFlags.length === 0
  ) {
    return [];
  }
  const out: Block[] = [
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      children: [
        new TextRun(
          t(
            "4. Compliance & citations",
            "4. Conformité et citations",
            locale,
          ),
        ),
      ],
    }),
  ];
  if (decision.complianceFlags.length > 0) {
    out.push(
      new Paragraph({
        children: [
          new TextRun({
            text: t("Flags: ", "Indicateurs : ", locale),
            italics: true,
            color: MUTED_HEX,
          }),
          new TextRun({ text: decision.complianceFlags.join(", ") }),
        ],
      }),
    );
  }
  for (const c of decision.citationsUsed) {
    out.push(
      new Paragraph({
        numbering: { reference: "wp-list", level: 0 },
        children: [
          new TextRun({ text: `${c.title} — ` }),
          new TextRun({ text: c.citation, italics: true }),
        ],
      }),
    );
  }
  return out;
}

function buildSignatureBlock(locale: Locale): Block[] {
  return [
    new Paragraph({ spacing: { before: 480 }, children: [new TextRun("")] }),
    new Paragraph({
      heading: HeadingLevel.HEADING_3,
      children: [
        new TextRun(
          t(
            "Signed for Vendor (Dunder AI Inc.)",
            "Signé pour le Fournisseur (Dunder AI Inc.)",
            locale,
          ),
        ),
      ],
    }),
    new Paragraph({
      children: [new TextRun({ text: "_________________________________" })],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: t(
            "Sarah Chen, Co-founder & COO",
            "Sarah Chen, Cofondatrice et Cheffe des opérations",
            locale,
          ),
        }),
      ],
    }),
  ];
}
